### ISSUE TITLE
Allow ignoring unchanged values

### ISSUE THREAD

**Issue by ps2goat** [nearform/temporal_tables#10]
I've been using this for awhile, and it works well. However, I'd like to see an option to ignore any unchanged rows for simplicity's sake.  We have issues with the amount of records stored in the history tables due to updates where no information has changed.

I agree that the best place for this is technically in the app code, but that would be more tedious and involve numerous apps and table/entity checks.  Putting the check in the versioning function itself seems like the best place (at least within our tech stack) for speed of development.

**Comment by paolochiodi** [comment]
The PR with the proposed change has been merged.
