### ISSUE TITLE
does not work for table names with CamelCase

### ISSUE THREAD

**Issue by yktv4** [nearform/temporal_tables#16]
### Issue:
These procedures don't work if your table names are in CamelCase.

### Environment:
- Postgres 12.1

### Explanation:
Current implementations of procedures make some assumptions that you have to comply with:
- your table name should be in snake_case
- you are allowed to pass schema within second argument of `versioning` function using dot notation like this: `public.origin_table`
Unfortunately it all breaks if you have your table name in camel case like this: `OriginTable` because of the following:
- in order to use PG identifiers in camel case, you have to quote them with double quotes (like this: `INSERT INTO "OriginTable"...`).
- internally procedures try to leverage `quote_ident` PG function to do this, but the implementation is incorrect in some places. specifically `versioning_function_nochecks` works correctly around `EXECUTE ('INSERT INTO ' ||` block, but fails on the previous lines at `WHERE  attrelid = history_table::regclass` due to not using `quote_ident` function here.

### How I fixed it:
- I first tried to build the correct `quote_ident` pipeline for the second argument of `versioning` function to allow for different values to be passed such as: `'history_table', 'public.history_table', 'HistoryTable', '"HistoryTable"',  'public."HistoryTable"', '"public"."HistoryTable"', 'public.HistoryTable', etc`.
- the code of acquiring the correct identifier involved: splitting by `.`, trimming both parts of any quotes, correctly quoting both parts with `quote_ident` PG function. all that multiplied by 2 because one may or may not pass the schema. I didn't want to make a reusable function just for that to not clutter the PG function name scope with seemingly unrelated function.
- when I saw how much code I need to add into the procedure to allow this, I thought that correct passing of identifier is out of scope of `temporal_tables` procedures and should be imposed on the user.
- I then tested the original `temporal_tables` PG extension and found that it did not work if I passed `'HistoryTable'` as a second argument either. It only worked if I passed `'"HistoryTable"'`. It proves that the original PG extension also imposed that onto user and did not try to handle it itself.
- I proceeded to write a test case and implementation fixes (see PR attached).

**Comment by paolochiodi** [comment]
Fixed by https://github.com/nearform/temporal_tables/pull/17 and https://github.com/nearform/temporal_tables/pull/21.

Thanks for the report and the PR (and the patience).

**Comment by yktv4** [comment]
@paolochiodi always my pleasure. thanks for writing the library in the first place!
