### ISSUE TITLE
Tables need to be fully qualified by schema.

### ISSUE THREAD

**Issue by joeandaverde** [nearform/temporal_tables#3]
I get a relation does not exist error here:

```...attrelid = TG_TABLE_NAME::regclass...```

This needs to take into account the schema of the table that caused the trigger.

**Comment by paolochiodi** [comment]
Hi, 
thank you for reporting this error. 

I'll work on a test case replicating it and will check your PR with it.

**Comment by paolochiodi** [comment]
Fixed in version 0.2.0
