### ISSUE TITLE
set_system_time is not supported

### ISSUE THREAD

**Issue by jgm-ktg** [nearform/temporal_tables#31]
The original temporal_tables extension defined set_system_time:

https://github.com/arkhipov/temporal_tables#advanced-usage

I cannot use my code without it!  Any chance of adding this simulation of the original as well?

**Comment by radomird** [comment]
Hi @jgm-ktg can you take a look at the PR? 
I've implemented the requested missing feature. Let me know if this would suite your needs. 

Thanks.

**Comment by jgm-ktg** [comment]
> Hi @jgm-ktg can you take a look at the PR? I've implemented the requested missing feature. Let me know if this would suite your needs.
> 
> Thanks.

Thank you!  I can't make time to look at this immediately but will shortly.  Thanks again...

**Comment by simoneb** [comment]
@jgm-ktg did you get a chance to look at this?

**Comment by jgm-ktg** [comment]
Not yet, but I am very grateful for the work and will asap!

**Comment by simoneb** [comment]
@jgm-ktg did you have a chance to look into this?

**Comment by simoneb** [comment]
@radomird thanks for picking this up again!
