### ISSUE TITLE
ignore_unchanged_values=false does not work

### ISSUE THREAD

**Issue by kilterskjalg** [nearform/temporal_tables#59]
Hi guys - thanks for the great repo.

Seems to me `range_lower` never gets set unless `ignore_unchanged_values=true.`

Also wondering how `ignore_unchaged_values` can ever be anything but null when it is defined as ` ignore_unchanged_values := TG_ARGV[3];` (i.e fourth parameter) and the function is called as per the readme with three parameters.

**Comment by simoneb** [comment]
Can you provide a repro please?

**Comment by kilterskjalg** [comment]
Try this:
```sql
BEGIN;
create table test_table (
  id integer primary key generated by default as identity,
  test text,
  sys_period tstzrange not null default tstzrange(CURRENT_TIMESTAMP, null)
);

create table test_table_history (LIKE test_table);

create trigger test_table_versioning_trigger
before insert or update or delete on test_table
for each row EXECUTE procedure versioning(
  'sys_period', 'test_table_history', false
);

insert into test_table(test) values ('hello');
COMMIT;

select pg_sleep(5);
delete from test_table;
select * from test_table_history; -- observe only one timestamp in time range

-- drop table test_table;
-- drop table test_table_history;
```

**Comment by ovhemert** [comment]
There might be a bit of a confusion here in the arguments passed to the trigger.

Basic creation of the trigger as per examples is done with 3 arguments which map to `TG_ARG[0] - TG_ARG[2]`.
The 3rd argument here is causing the lower range to be left out when set to `false` using [this condition](https://github.com/nearform/temporal_tables/blob/master/versioning_function.sql#L128-L134). 
This is the result of your example:
```
create trigger test_table_versioning_trigger
before insert or update or delete on test_table
for each row EXECUTE procedure versioning(
  'sys_period', 'test_table_history', false
);
```

During the creation of the trigger there is also a 4th argument (`TG_ARG[3]`) that controls the [Ignore updates without actual change](https://github.com/nearform/temporal_tables#ignore-unchanged-values). That parameter is by default set to `false`, but can be set to `true` during creation of the trigger. In the sql-file this maps to the `ignore_unchanges_values` on [line 54](https://github.com/nearform/temporal_tables/blob/master/versioning_function.sql#L54).
```
CREATE TRIGGER versioning_trigger
BEFORE INSERT OR UPDATE OR DELETE ON subscriptions
FOR EACH ROW EXECUTE PROCEDURE versioning(
  'sys_period', 'subscriptions_history', true, true
);
```

This means that if you want to use the functionality to ignore unchanged values, please add the 4th parameter (set to `true`) to you trigger creation.
