### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by spkprav** [nearform/temporal_tables#65]
I did exactly as in the readme in postgres v14.1 in my local and it didn't work. I immediately spawned a new RDS in AWS with v16.2 and followed the readme and it still didn't work. The history table is always empty, and the data isn't propagating to it.

Thank you for your help in advance.

**Comment by simoneb** [comment]
Yes, this is working. Without a repro we're not going to be able to troubleshoot your issue I'm afraid, my best guess is that you didn't follow the instructions closely.

**Comment by eshepelyuk** [comment]
I've been trying it for about an hour and noticed a pattern.

The record is inserted into history table only after an `UPDATE` or `DELETE` statement. 
Records are not inserted on `INSERT`.

If this an expected behavior ?

**Comment by simoneb** [comment]
> If this an expected behavior?

Yes, if the record is new, there's no history.

**Comment by eshepelyuk** [comment]
> > If this an expected behavior?
> 
> Yes, if the record is new, there's no history.

ok, it was a bit confusing, so I also initially thought it's not working.
but ofc this behaviour makes sense.

**Comment by spkprav** [comment]
This issue can be closed, as it started to work fine, it was a configuration issue from my side.
