### ISSUE TITLE
How to back-fill history items from the past?

### ISSUE THREAD

**Issue by DefiantCatgirl** [nearform/temporal_tables#66]
We've got a use case where live data is streamed to the database, but also occasionally older updates will be sent as well to back-fill the historical data.

E.g., slightly modifying the readme sample:

``` sql
SELECT set_system_time('2001-12-31 23:59:59');
INSERT INTO subscriptions (name, state) VALUES ('test2', '2001 update');
SELECT set_system_time('2000-12-31 23:59:59');
UPDATE subscriptions SET state = '2000 update' WHERE name = 'test2';
SELECT set_system_time('1999-12-31 23:59:59');
UPDATE subscriptions SET state = '1999 update' WHERE name = 'test2';
```

The current behavior results in:

| name | state      | sys_period        |
|-------|---------------|-------------------------------------------------------------------|
| test2 | 2001 update      | ["2001-12-31 23:59:59+00","2001-12-31 23:59:59.000001+00")        |
| test2 | 2000 update       | ["2001-12-31 23:59:59.000001+00","2001-12-31 23:59:59.000002+00") |
| test2 | 1999 update | ["2001-12-31 23:59:59.000002+00","2001-12-31 23:59:59.000003+00") |

While what I would ideally want is

| name | state      | sys_period        |
|-------|---------------|-------------------------------------------------------------------|
| test2 | 1999 update | ["1999-12-31 23:59:59+00","2000-12-31 23:59:59+00")       |
| test2 | 2000 update | ["2000-12-31 23:59:59+00","2001-12-31 23:59:59+00") |
| test2 | 2001 update | ["2001-12-31 23:59:59+00","2001-12-31 23:59:59.000001+00") |

Is there a way to modify the versioning function so that it supports inserting historical values, or would it be too impractical to do with this extension? I'm unfortunately too inexperienced with SQL to try and figure it out by myself...

**Comment by simoneb** [comment]
If your system is streaming updates and also older values, in an unpredictable order, I feel that you're looking for a custom solution, because although the purpose is similar, the intention of this extension is that the historical data is created from changes happening in the main table. You may still inspire from how we do it here, but unless you think otherwise, it doesn't look like this behavior would fit in the extension.
