### ISSUE TITLE
Missing updates when deleting row in the same transaction

### ISSUE THREAD

**Issue by jakufort** [nearform/temporal_tables#69]
Hi

In short, I would like to track who modified or removed given record.

As an example, let's say I have a table
```sql
create table users (
  email varchar primary key,
  modified_by varchar not null,
  sys_period tstzrange NOT NULL DEFAULT tstzrange(current_timestamp, null);
);

-- I'm omitting temporal_tables setup, you can assume that I have `users_history` table defined
```

Now, when I run
```sql
-- first transaction
insert into users values ("someone@acme.com", "admin@acme.com");

-- second transaction
update users set modified_by = "second-admin@acme.com" where email = "someone@acme.com";
delete from users where email = "someone@acme.com";
```

I'll get single record in `users_history` table
```
someone@acme.com; admin@acme.com; [timestamp-1 timestamp-2]
```
instead of 
```
someone@acme.com; admin@acme.com [timestamp-1 timestamp-2]
someone@amce.com; second-admin@acme.com [timestamp-2 (timestamp-2 + 1 microsecond)]
```

From what I understand what happens is:
- insert doesn't save anything in history (since there's no history to preserve yet)
- update inserts old row (with `admin@acme.com`) into history table (as it should)
- delete doesn't insert row into history table due to [transaction check](https://github.com/nearform/temporal_tables/blob/master/versioning_function_nochecks.sql#L45)

I understand that it's not a bug per se (I did find information that this is present to [be backwards compatible with native extension](https://github.com/nearform/temporal_tables/issues/27#issuecomment-926416333)), so this "ticket" is more of a question 😅  

How I've "fixed" it was to remove transaction check from `versioning` function and I'm wondering if this is a "intended" solution or maybe I'm missing something?

I know I could run update and delete in separate transactions but in this case it doesn't make sense - it should be all-or-nothing.

**Comment by simoneb** [comment]
Hi @jakufort , I guess you answered your own question. The behavior of this implementation tries to stay consistent with the original behavior, therefore any changes happening within the same transactions are invisible to the history table except the end result of the transaction. We're not planning to deviate further from the original behavior, unless there's a strong demand for that, in which case we may introduce this under a configuration option. At the moment I don't see a compelling reason to do that.
