### ISSUE TITLE
Lower range is not set in history table when including current version

### ISSUE THREAD

**Issue by jmlacroix** [nearform/temporal_tables#74]
Hi, thanks for this great library!

I'm using the latest release of temporal_tables with *include current version* enabled:

`versioning('sys_period', 'locations_history', true, true, true);`

I have an issue when updating a record where the starting date from the range in my history table is not set:

![CleanShot 2024-11-15 at 17 13 49](https://github.com/user-attachments/assets/0a0babbc-e481-45c3-811b-56f5131cec1e)

If I manually define `range_lower` on line 205:

`EXECUTE format('SELECT lower($1.%I)', sys_period) USING OLD INTO range_lower;`

I then get the result I expect:

![CleanShot 2024-11-15 at 17 10 16](https://github.com/user-attachments/assets/fd2e53f0-092c-491e-9a98-359cae3065f4)

It looks like the lower range is not updated properly because `range_lower` is not defined, as it is only defined when not including the current version (line 136).

Let me know if I can provide more context or info to investigate.

**Comment by kieranswhite** [comment]
Hi @jmlacroix this has now been released as per the above comment from our bot. 

Thank you for raising the issue it should now been resolved :)

**Comment by jmlacroix** [comment]
Thanks for the quick resolution @kieranswhite and @simoneb ! 🙏
